In [168]:
import pandas as pd
import numpy as np

In [169]:
user_profile_df = pd.read_csv('userprofile.csv')
user_cuisine_df = pd.read_csv('usercuisine.csv')

In [170]:
user_profile_df_temp = user_profile_df.drop(['latitude','longitude','weight','height','birth_year'],axis=1)

In [171]:
for column in user_profile_df_temp.columns:
  user_profile_df_temp[column] = user_profile_df_temp[column].replace(to_replace='?', value=user_profile_df_temp[column].mode()[0])

In [172]:
user_profile_df_temp

,userID,smoker,drink_level,dress_preference,ambience,transport,marital_status,hijos,interest,personality,religion,activity,color,budget
0,U1001,false,abstemious,informal,family,on foot,single,independent,variety,thrifty-protector,none,student,black,medium
1,U1002,false,abstemious,informal,family,public,single,independent,technology,hunter-ostentatious,Catholic,student,red,low
2,U1003,false,social drinker,formal,family,public,single,independent,none,hard-worker,Catholic,student,blue,low
3,U1004,false,abstemious,informal,family,public,single,independent,variety,hard-worker,none,professional,green,medium
4,U1005,false,abstemious,no preference,family,public,single,independent,none,thrifty-protector,Catholic,student,black,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,U1134,false,casual drinker,no preference,family,public,single,independent,variety,hard-worker,Catholic,student,black,medium
134,U1135,false,casual drinker,informal,family,on foot,single,kids,variety,hunter-ostentatious,Catholic,student,purple,low
135,U1136,true,social drinker,no preference,friends,car owner,single,independent,retro,thrifty-protector,Catholic,student,black,low
136,U1137,false,social drinker,formal,family,public,single,independent,eco-friendly,hard-worker,Catholic,student,blue,low
137,U1138,false,social drinker,formal,friends,public,single,independent,variety,thrifty-protector,none,student,blue,medium

In [173]:
def jaccard_similarity(set1, set2):
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union

In [174]:
def jaccard_similarity_matrix(data):
    num_items = len(data)
    similarity_matrix = [[0] * num_items for _ in range(num_items)]

    for i in range(num_items):
        for j in range(num_items):
            if i == j:
                similarity_matrix[i][j] = 1.0
            else:
                similarity_matrix[i][j] = jaccard_similarity(set(data[i]), set(data[j]))

    return similarity_matrix

In [175]:
jaccard_similarity_matrix = jaccard_similarity_matrix(np.array(user_profile_df_temp.drop(['userID'],axis=1)))

In [176]:
user_profile_similarity_df = pd.DataFrame(jaccard_similarity_matrix, index=user_profile_df_temp['userID'], columns=user_profile_df_temp['userID'])

In [177]:
user_profile_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.368421,0.300000,0.529412,0.625000,0.300000,0.368421,0.181818,0.529412,0.181818,...,0.368421,0.470588,0.181818,0.388889,0.470588,0.444444,0.368421,0.238095,0.238095,0.444444
U1002,0.368421,1.000000,0.444444,0.368421,0.444444,0.130435,0.444444,0.444444,0.300000,0.130435,...,0.300000,0.388889,0.040000,0.315789,0.315789,0.368421,0.444444,0.238095,0.444444,0.238095
U1003,0.300000,0.444444,1.000000,0.368421,0.444444,0.368421,0.368421,0.625000,0.300000,0.238095,...,0.368421,0.470588,0.181818,0.470588,0.388889,0.444444,0.300000,0.300000,0.857143,0.529412
U1004,0.529412,0.368421,0.368421,1.000000,0.444444,0.300000,0.300000,0.300000,0.368421,0.238095,...,0.300000,0.562500,0.130435,0.470588,0.470588,0.444444,0.238095,0.083333,0.300000,0.368421
U1005,0.625000,0.444444,0.444444,0.444444,1.000000,0.300000,0.368421,0.300000,0.444444,0.238095,...,0.444444,0.666667,0.238095,0.388889,0.562500,0.625000,0.238095,0.368421,0.368421,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.444444,0.368421,0.444444,0.444444,0.625000,0.368421,0.444444,0.368421,0.368421,0.238095,...,0.444444,0.562500,0.238095,0.470588,0.470588,1.000000,0.368421,0.300000,0.444444,0.368421
U1135,0.368421,0.444444,0.300000,0.238095,0.238095,0.130435,0.529412,0.238095,0.444444,0.130435,...,0.368421,0.190476,0.083333,0.250000,0.190476,0.368421,1.000000,0.181818,0.300000,0.181818
U1136,0.238095,0.238095,0.300000,0.083333,0.368421,0.444444,0.300000,0.300000,0.181818,0.238095,...,0.368421,0.190476,0.368421,0.136364,0.250000,0.300000,0.181818,1.000000,0.300000,0.300000
U1137,0.238095,0.444444,0.857143,0.300000,0.368421,0.300000,0.368421,0.625000,0.300000,0.181818,...,0.300000,0.388889,0.181818,0.388889,0.315789,0.444444,0.300000,0.300000,1.000000,0.444444
U1138,0.444444,0.238095,0.529412,0.368421,0.444444,0.529412,0.368421,0.368421,0.368421,0.300000,...,0.529412,0.388889,0.238095,0.470588,0.315789,0.368421,0.181818,0.300000,0.444444,1.000000

In [178]:
user_profile_df_body = user_profile_df[['userID','weight','height']]

In [179]:
user_profile_df_body

    userID  weight  height
0    U1001      69    1.77
1    U1002      40    1.87
2    U1003      60    1.69
3    U1004      44    1.53
4    U1005      65    1.69
..     ...     ...     ...
133  U1134      52    1.65
134  U1135      66    1.54
135  U1136      50    1.60
136  U1137      72    1.78
137  U1138      54    1.55

[138 rows x 3 columns]

In [180]:
def manhattan_distance(vec1, vec2):
    return sum(abs(a - b) for a, b in zip(vec1, vec2))

In [181]:
def manhattan_similarity_matrix(data):
    num_points = len(data)
    similarity_matrix = [[0] * num_points for _ in range(num_points)]

    for i in range(num_points):
        for j in range(num_points):
            if i == j:
                similarity_matrix[i][j] = 1.0
            else:
                similarity_matrix[i][j] = 1 / (1 + manhattan_distance(data[i], data[j]))

    return similarity_matrix

In [182]:
body_manhattan_similarity_matrix = manhattan_similarity_matrix(np.array(user_profile_df_body.drop('userID',axis=1)))

In [183]:
user_profile_body_similarity_df = pd.DataFrame(body_manhattan_similarity_matrix, index=user_profile_df_body['userID'], columns=user_profile_df_body['userID'])

In [184]:
user_profile_body_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.033223,0.099206,0.038110,0.196850,0.142248,0.098232,0.487805,0.142653,0.033223,...,0.925926,0.032712,0.045393,0.065920,0.098039,0.055188,0.236407,0.049579,0.249377,0.061652
U1002,0.033223,1.000000,0.047214,0.187266,0.038197,0.027724,0.046992,0.034305,0.027709,0.833333,...,0.033135,0.598802,0.019581,0.061463,0.046948,0.075643,0.036590,0.088731,0.030221,0.065274
U1003,0.099206,0.047214,1.000000,0.058275,0.166667,0.062073,0.909091,0.110742,0.062150,0.047574,...,0.100000,0.046533,0.032144,0.164204,0.892857,0.110619,0.139860,0.090171,0.076394,0.140056
U1004,0.038110,0.187266,0.058275,1.000000,0.045126,0.030989,0.058617,0.039698,0.031008,0.194553,...,0.038226,0.187617,0.021155,0.082850,0.058685,0.109649,0.043459,0.141443,0.034188,0.090744
U1005,0.196850,0.038197,0.166667,0.045126,1.000000,0.090009,0.163934,0.248139,0.090171,0.038432,...,0.200000,0.037750,0.038300,0.090171,0.163399,0.071225,0.465116,0.062150,0.123609,0.082372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.055188,0.075643,0.110619,0.109649,0.071225,0.041408,0.110375,0.058582,0.041442,0.076805,...,0.055432,0.074349,0.025543,0.246914,0.110132,1.000000,0.066181,0.327869,0.047326,0.322581
U1135,0.236407,0.036590,0.139860,0.043459,0.465116,0.097466,0.141844,0.314465,0.097656,0.036860,...,0.240964,0.036576,0.039588,0.082919,0.142248,0.066181,1.000000,0.058617,0.138122,0.076864
U1136,0.049579,0.088731,0.090171,0.141443,0.062150,0.038168,0.090827,0.052301,0.038197,0.090334,...,0.049776,0.087719,0.024272,0.166667,0.090662,0.327869,0.058617,1.000000,0.043141,0.198020
U1137,0.249377,0.030221,0.076394,0.034188,0.123609,0.248756,0.075815,0.197628,0.250000,0.030202,...,0.244499,0.029780,0.052576,0.055006,0.075700,0.047326,0.138122,0.043141,1.000000,0.052002
U1138,0.061652,0.065274,0.140056,0.090744,0.082372,0.044944,0.142045,0.065920,0.044984,0.066138,...,0.061958,0.065147,0.026846,0.487805,0.142450,0.322581,0.076864,0.198020,0.052002,1.000000

In [185]:
user_profile_df_location = user_profile_df[['userID','latitude','longitude']]

In [186]:
user_profile_df_location

    userID   latitude   longitude
0    U1001  22.139997 -100.978803
1    U1002  22.150087 -100.983325
2    U1003  22.119847 -100.946527
3    U1004  18.867000  -99.183000
4    U1005  22.183477 -100.959891
..     ...        ...         ...
133  U1134  22.149654 -100.998610
134  U1135  22.170396 -100.949936
135  U1136  22.149607 -100.997235
136  U1137  22.144803 -100.944623
137  U1138  22.152884 -100.939663

[138 rows x 3 columns]

In [187]:
location_manhattan_similarity_matrix = manhattan_similarity_matrix(np.array(user_profile_df_location.drop('userID',axis=1)))

In [188]:
user_profile_location_similarity_df = pd.DataFrame(location_manhattan_similarity_matrix, index=user_profile_df_location['userID'], columns=user_profile_df_location['userID'])

In [189]:
user_profile_location_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.985598,0.950186,0.164777,0.941272,0.985999,0.941549,0.932836,0.969862,0.933918,...,0.225553,0.225286,0.934923,0.985999,0.163476,0.971379,0.944050,0.972723,0.962477,0.950546
U1002,0.985598,1.000000,0.937174,0.164381,0.946231,0.999588,0.928771,0.920292,0.983804,0.946839,...,0.225836,0.225569,0.922323,0.999588,0.163086,0.984525,0.949039,0.985814,0.957867,0.955604
U1003,0.950186,0.937174,1.000000,0.166213,0.928510,0.937536,0.990438,0.974794,0.922934,0.890326,...,0.226171,0.225903,0.948787,0.937536,0.164889,0.924308,0.948804,0.925525,0.973843,0.961630
U1004,0.164777,0.164381,0.166213,1.000000,0.164113,0.164393,0.166480,0.166756,0.163938,0.162878,...,0.169183,0.169033,0.166689,0.164393,0.919355,0.163981,0.164736,0.164019,0.165579,0.165493
U1005,0.941272,0.946231,0.928510,0.164113,1.000000,0.946444,0.920261,0.911936,0.948221,0.955849,...,0.228772,0.228498,0.913931,0.946444,0.162822,0.932364,0.977483,0.933520,0.948819,0.951637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.971379,0.984525,0.924308,0.163981,0.932364,0.984295,0.916133,0.907883,0.982381,0.960344,...,0.225037,0.224772,0.909859,0.984295,0.162692,1.000000,0.935090,0.998580,0.944432,0.941463
U1135,0.944050,0.949039,0.948804,0.164736,0.977483,0.949253,0.940192,0.931505,0.951040,0.935256,...,0.228608,0.228334,0.933586,0.949253,0.163435,0.935090,1.000000,0.936252,0.970021,0.972966
U1136,0.972723,0.985814,0.925525,0.164019,0.933520,0.985583,0.917329,0.909056,0.983664,0.959034,...,0.225105,0.224839,0.911038,0.985583,0.162730,0.998580,0.936252,1.000000,0.945702,0.942641
U1137,0.962477,0.957867,0.973843,0.165579,0.948819,0.958245,0.968330,0.959117,0.942997,0.908982,...,0.227553,0.227282,0.961323,0.958245,0.164264,0.944432,0.970021,0.945702,1.000000,0.987127
U1138,0.950546,0.955604,0.961630,0.165493,0.951637,0.955821,0.965412,0.956254,0.945780,0.911568,...,0.228231,0.227958,0.958447,0.955821,0.164180,0.941463,0.972966,0.942641,0.987127,1.000000

In [190]:
user_cuisine_df

    userID           Rcuisine
0    U1001           American
1    U1002            Mexican
2    U1003            Mexican
3    U1004             Bakery
4    U1004   Breakfast-Brunch
..     ...                ...
325  U1135           Southern
326  U1135  Dessert-Ice_Cream
327  U1136            Mexican
328  U1137            Mexican
329  U1138           Pizzeria

[330 rows x 2 columns]

In [191]:
user_cuisines = user_cuisine_df.groupby('userID')['Rcuisine'].apply(set)

In [192]:
num_users = len(user_cuisines)
similarity_matrix = [[0] * num_users for _ in range(num_users)]

In [193]:
for i, user1 in enumerate(user_cuisines.index):
    for j, user2 in enumerate(user_cuisines.index):
        if i == j:
            similarity_matrix[i][j] = 1.0
        else:
            similarity_matrix[i][j] = jaccard_similarity(user_cuisines[user1], user_cuisines[user2])

In [194]:
user_cuisine_similarity_df = pd.DataFrame(similarity_matrix, index=user_profile_df_temp['userID'], columns=user_profile_df_temp['userID'])

In [195]:
user_cuisine_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.100000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009709,0.000000,0.000000,0.000000
U1002,0.000000,1.000000,1.000000,0.111111,0.000000,1.000000,0.000000,0.100000,0.142857,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.009709,1.000000,1.000000,0.000000
U1003,0.000000,1.000000,1.000000,0.111111,0.000000,1.000000,0.000000,0.100000,0.142857,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.009709,1.000000,1.000000,0.000000
U1004,0.000000,0.111111,0.111111,1.000000,0.000000,0.111111,0.000000,0.187500,0.230769,0.111111,...,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.087379,0.111111,0.111111,0.000000
U1005,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.100000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009709,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.000000,1.000000,1.000000,0.111111,0.000000,1.000000,0.000000,0.100000,0.142857,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.009709,1.000000,1.000000,0.000000
U1135,0.009709,0.009709,0.009709,0.087379,0.009709,0.009709,0.009709,0.097087,0.067961,0.009709,...,0.009709,0.009709,0.009709,0.009709,0.009709,0.009709,1.000000,0.009709,0.009709,0.009709
U1136,0.000000,1.000000,1.000000,0.111111,0.000000,1.000000,0.000000,0.100000,0.142857,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.009709,1.000000,1.000000,0.000000
U1137,0.000000,1.000000,1.000000,0.111111,0.000000,1.000000,0.000000,0.100000,0.142857,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.009709,1.000000,1.000000,0.000000
U1138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009709,0.000000,0.000000,1.000000

In [196]:
pf_w = 0.1
cui_w = 0.7
loc_w = 0.1
bod_w = 0.1

In [197]:
user_similarity_df = cui_w*user_cuisine_similarity_df + pf_w*user_profile_similarity_df + loc_w*user_profile_location_similarity_df + bod_w*user_profile_body_similarity_df

In [198]:
user_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.138724,0.134939,0.073230,0.876312,0.142825,0.140820,0.230246,0.164193,0.114896,...,0.151990,0.072859,0.116213,0.144081,0.073210,0.147101,0.161684,0.126040,0.144995,0.145664
U1002,0.138724,1.000000,0.842883,0.149785,0.142887,0.815775,0.142021,0.209904,0.231151,0.891061,...,0.755897,0.821326,0.798190,0.837684,0.752582,0.842859,0.149803,0.831264,0.843253,0.125897
U1003,0.134939,0.842883,1.000000,0.137069,0.153962,0.836803,0.226795,0.241054,0.228508,0.817600,...,0.769459,0.774302,0.816275,0.857233,0.844663,0.847937,0.145663,0.831570,0.890738,0.163110
U1004,0.073230,0.149785,0.137069,1.000000,0.065368,0.127316,0.052510,0.181895,0.217875,0.137330,...,0.128519,0.169693,0.109606,0.149561,0.222641,0.149585,0.105794,0.116657,0.127754,0.062466
U1005,0.876312,0.142887,0.153962,0.065368,1.000000,0.133645,0.145262,0.216008,0.148284,0.123238,...,0.087322,0.093291,0.119033,0.142550,0.088872,0.162859,0.174866,0.136409,0.144085,0.147845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.147101,0.842859,0.847937,0.149585,0.162859,0.839412,0.147095,0.203489,0.239224,0.827524,...,0.772491,0.786162,0.817350,0.870180,0.774341,1.000000,0.143765,0.862645,0.843620,0.163246
U1135,0.161684,0.149803,0.145663,0.105794,0.174866,0.124511,0.167941,0.216368,0.196887,0.117051,...,0.090595,0.052335,0.112447,0.135013,0.056412,0.143765,1.000000,0.124465,0.147610,0.129961
U1136,0.126040,0.831264,0.831570,0.116657,0.136409,0.846820,0.130816,0.196136,0.220368,0.828746,...,0.764330,0.750303,0.830373,0.828861,0.750339,0.862645,0.124465,1.000000,0.828884,0.144066
U1137,0.144995,0.843253,0.890738,0.127754,0.144085,0.850700,0.141257,0.248175,0.249300,0.812100,...,0.777205,0.764595,0.819572,0.840214,0.755575,0.843620,0.147610,0.828884,1.000000,0.148357
U1138,0.145664,0.125897,0.163110,0.062466,0.147845,0.153018,0.147588,0.139059,0.135919,0.127771,...,0.081960,0.068199,0.122339,0.191421,0.062242,0.163246,0.129961,0.144066,0.148357,1.000000

In [199]:
user_cuisine_matrix = user_cuisine_df.pivot_table(index='userID', columns='Rcuisine', aggfunc='size', fill_value=0)

In [200]:
user_cuisine_matrix

Rcuisine,Afghan,African,American,Armenian,Asian,Australian,Austrian,Bagels,Bakery,Bar,...,Swiss,Tapas,Tea_House,Tex-Mex,Thai,Tibetan,Tunisian,Turkish,Vegetarian,Vietnamese
userID,,,,,,,,,,,,,,,,,,,,,
U1001,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1004,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
U1005,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1135,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
U1136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1138,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [201]:
def get_top_k_cuisines_for_user(user_id, k=5):
    # Find similar users to the target user
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:k+5].index

    # Get the cuisines preferred by similar users
    top_k_cuisines = user_cuisine_matrix.loc[similar_users].sum().sort_values(ascending=False)[:k].index

    return top_k_cuisines

In [202]:
user_id_to_recommend = 'U1016'  # Replace with the user ID you want to recommend cuisines for
top_k_cuisines = get_top_k_cuisines_for_user(user_id_to_recommend, k=5)
print(f"Top-K cuisines for user {user_id_to_recommend}:")
print(top_k_cuisines)

Top-K cuisines for user U1016:
Index(['American', 'Mexican', 'Latin_American', 'Cafeteria', 'Hot_Dogs'], dtype='object', name='Rcuisine')