In [53]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
user_profile_df = pd.read_csv('userprofile.csv')
user_cuisine_df = pd.read_csv('usercuisine.csv')

In [56]:
user_profile_df = user_profile_df[['userID', 'smoker', 'budget','drink_level']]

In [57]:
user_profile_df['smoker'] = user_profile_df['smoker'].replace(to_replace='?', value=user_profile_df['smoker'].mode()[0])

In [58]:
user_profile_df['budget'] = user_profile_df['budget'].replace(to_replace='?', value=user_profile_df['budget'].mode()[0])

In [59]:
user_profile_df['drink_level'].unique()

array(['abstemious', 'social drinker', 'casual drinker'], dtype=object)

In [60]:
user_profile_df

    userID smoker  budget     drink_level
0    U1001  false  medium      abstemious
1    U1002  false     low      abstemious
2    U1003  false     low  social drinker
3    U1004  false  medium      abstemious
4    U1005  false  medium      abstemious
..     ...    ...     ...             ...
133  U1134  false  medium  casual drinker
134  U1135  false     low  casual drinker
135  U1136   true     low  social drinker
136  U1137  false     low  social drinker
137  U1138  false  medium  social drinker

[138 rows x 4 columns]

In [61]:
user_cuisine_df

    userID           Rcuisine
0    U1001           American
1    U1002            Mexican
2    U1003            Mexican
3    U1004             Bakery
4    U1004   Breakfast-Brunch
..     ...                ...
325  U1135           Southern
326  U1135  Dessert-Ice_Cream
327  U1136            Mexican
328  U1137            Mexican
329  U1138           Pizzeria

[330 rows x 2 columns]

In [62]:
user_profile_df['smoker'] = user_profile_df['smoker'].replace(to_replace='false', value=0)
user_profile_df['smoker'] = user_profile_df['smoker'].replace(to_replace='true', value=1)

In [63]:
user_profile_df['budget'] = user_profile_df['budget'].replace(to_replace='low', value=0)
user_profile_df['budget'] = user_profile_df['budget'].replace(to_replace='medium', value=1)
user_profile_df['budget'] = user_profile_df['budget'].replace(to_replace='high', value=2)

In [64]:
user_profile_df['drink_level'] = user_profile_df['drink_level'].replace(to_replace='abstemious', value=0)
user_profile_df['drink_level'] = user_profile_df['drink_level'].replace(to_replace='social drinker', value=1)
user_profile_df['drink_level'] = user_profile_df['drink_level'].replace(to_replace='casual drinker', value=2)

In [65]:
user_profile_df

    userID  smoker  budget  drink_level
0    U1001       0       1            0
1    U1002       0       0            0
2    U1003       0       0            1
3    U1004       0       1            0
4    U1005       0       1            0
..     ...     ...     ...          ...
133  U1134       0       1            2
134  U1135       0       0            2
135  U1136       1       0            1
136  U1137       0       0            1
137  U1138       0       1            1

[138 rows x 4 columns]

In [66]:
user_profile_similarity = cosine_similarity(user_profile_df[['smoker', 'budget','drink_level']])
user_profile_similarity_df = pd.DataFrame(user_profile_similarity, index=user_profile_df['userID'], columns=user_profile_df['userID'])

In [67]:
user_profile_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.0,0.000000,1.000000,1.000000,0.577350,0.000000,0.000000,1.000000,0.707107,...,0.000000,1.000000,0.577350,0.447214,1.000000,0.447214,0.000000,0.000000,0.000000,0.707107
U1002,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
U1003,0.000000,0.0,1.000000,0.000000,0.000000,0.577350,1.000000,1.000000,0.000000,0.707107,...,1.000000,0.000000,0.577350,0.894427,0.000000,0.894427,1.000000,0.707107,1.000000,0.707107
U1004,1.000000,0.0,0.000000,1.000000,1.000000,0.577350,0.000000,0.000000,1.000000,0.707107,...,0.000000,1.000000,0.577350,0.447214,1.000000,0.447214,0.000000,0.000000,0.000000,0.707107
U1005,1.000000,0.0,0.000000,1.000000,1.000000,0.577350,0.000000,0.000000,1.000000,0.707107,...,0.000000,1.000000,0.577350,0.447214,1.000000,0.447214,0.000000,0.000000,0.000000,0.707107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.447214,0.0,0.894427,0.447214,0.447214,0.774597,0.894427,0.894427,0.447214,0.948683,...,0.894427,0.447214,0.774597,1.000000,0.447214,1.000000,0.894427,0.632456,0.894427,0.948683
U1135,0.000000,0.0,1.000000,0.000000,0.000000,0.577350,1.000000,1.000000,0.000000,0.707107,...,1.000000,0.000000,0.577350,0.894427,0.000000,0.894427,1.000000,0.707107,1.000000,0.707107
U1136,0.000000,0.0,0.707107,0.000000,0.000000,0.816497,0.707107,0.707107,0.000000,0.500000,...,0.707107,0.000000,0.816497,0.632456,0.000000,0.632456,0.707107,1.000000,0.707107,0.500000
U1137,0.000000,0.0,1.000000,0.000000,0.000000,0.577350,1.000000,1.000000,0.000000,0.707107,...,1.000000,0.000000,0.577350,0.894427,0.000000,0.894427,1.000000,0.707107,1.000000,0.707107
U1138,0.707107,0.0,0.707107,0.707107,0.707107,0.816497,0.707107,0.707107,0.707107,1.000000,...,0.707107,0.707107,0.816497,0.948683,0.707107,0.948683,0.707107,0.500000,0.707107,1.000000

In [68]:
user_cuisine_matrix = user_cuisine_df.pivot_table(index='userID', columns='Rcuisine', aggfunc='size', fill_value=0)

In [69]:
user_cuisine_matrix

Rcuisine,Afghan,African,American,Armenian,Asian,Australian,Austrian,Bagels,Bakery,Bar,...,Swiss,Tapas,Tea_House,Tex-Mex,Thai,Tibetan,Tunisian,Turkish,Vegetarian,Vietnamese
userID,,,,,,,,,,,,,,,,,,,,,
U1001,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1004,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
U1005,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1135,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
U1136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1138,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
user_cuisine_similarity = cosine_similarity(user_cuisine_matrix)
user_cuisine_similarity_df = pd.DataFrame(user_cuisine_similarity, index=user_cuisine_matrix.index, columns=user_cuisine_matrix.index)

In [73]:
user_cuisine_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.316228,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.098533,0.000000,0.000000,0.000000
U1002,0.000000,1.000000,1.000000,0.333333,0.000000,1.000000,0.000000,0.316228,0.377964,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.098533,1.000000,1.000000,0.000000
U1003,0.000000,1.000000,1.000000,0.333333,0.000000,1.000000,0.000000,0.316228,0.377964,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.098533,1.000000,1.000000,0.000000
U1004,0.000000,0.333333,0.333333,1.000000,0.000000,0.333333,0.000000,0.316228,0.377964,0.333333,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.295599,0.333333,0.333333,0.000000
U1005,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.316228,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.098533,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.000000,1.000000,1.000000,0.333333,0.000000,1.000000,0.000000,0.316228,0.377964,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.098533,1.000000,1.000000,0.000000
U1135,0.098533,0.098533,0.098533,0.295599,0.098533,0.098533,0.098533,0.311588,0.260694,0.098533,...,0.098533,0.098533,0.098533,0.098533,0.098533,0.098533,1.000000,0.098533,0.098533,0.098533
U1136,0.000000,1.000000,1.000000,0.333333,0.000000,1.000000,0.000000,0.316228,0.377964,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.098533,1.000000,1.000000,0.000000
U1137,0.000000,1.000000,1.000000,0.333333,0.000000,1.000000,0.000000,0.316228,0.377964,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.098533,1.000000,1.000000,0.000000
U1138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.098533,0.000000,0.000000,1.000000

In [74]:
cuisine_weight = 0.8
profile_weight = 0.2

In [77]:
user_similarity_df = cuisine_weight*user_cuisine_similarity_df + profile_weight*user_profile_similarity_df

In [78]:
user_similarity_df

userID,U1001,U1002,U1003,U1004,U1005,U1006,U1007,U1008,U1009,U1010,...,U1129,U1130,U1131,U1132,U1133,U1134,U1135,U1136,U1137,U1138
userID,,,,,,,,,,,,,,,,,,,,,
U1001,1.000000,0.000000,0.000000,0.200000,1.000000,0.115470,0.000000,0.252982,0.200000,0.141421,...,0.000000,0.200000,0.115470,0.089443,0.200000,0.089443,0.078826,0.000000,0.000000,0.141421
U1002,0.000000,0.800000,0.800000,0.266667,0.000000,0.800000,0.000000,0.252982,0.302372,0.800000,...,0.800000,0.800000,0.800000,0.800000,0.800000,0.800000,0.078826,0.800000,0.800000,0.000000
U1003,0.000000,0.800000,1.000000,0.266667,0.000000,0.915470,0.200000,0.452982,0.302372,0.941421,...,1.000000,0.800000,0.915470,0.978885,0.800000,0.978885,0.278826,0.941421,1.000000,0.141421
U1004,0.200000,0.266667,0.266667,1.000000,0.200000,0.382137,0.000000,0.252982,0.502372,0.408088,...,0.266667,0.466667,0.382137,0.356109,0.466667,0.356109,0.236479,0.266667,0.266667,0.141421
U1005,1.000000,0.000000,0.000000,0.200000,1.000000,0.115470,0.000000,0.252982,0.200000,0.141421,...,0.000000,0.200000,0.115470,0.089443,0.200000,0.089443,0.078826,0.000000,0.000000,0.141421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U1134,0.089443,0.800000,0.978885,0.356109,0.089443,0.954919,0.178885,0.431868,0.391814,0.989737,...,0.978885,0.889443,0.954919,1.000000,0.889443,1.000000,0.257712,0.926491,0.978885,0.189737
U1135,0.078826,0.078826,0.278826,0.236479,0.078826,0.194296,0.278826,0.449271,0.208555,0.220248,...,0.278826,0.078826,0.194296,0.257712,0.078826,0.257712,1.000000,0.220248,0.278826,0.220248
U1136,0.000000,0.800000,0.941421,0.266667,0.000000,0.963299,0.141421,0.394404,0.302372,0.900000,...,0.941421,0.800000,0.963299,0.926491,0.800000,0.926491,0.220248,1.000000,0.941421,0.100000
U1137,0.000000,0.800000,1.000000,0.266667,0.000000,0.915470,0.200000,0.452982,0.302372,0.941421,...,1.000000,0.800000,0.915470,0.978885,0.800000,0.978885,0.278826,0.941421,1.000000,0.141421
U1138,0.141421,0.000000,0.141421,0.141421,0.141421,0.163299,0.141421,0.141421,0.141421,0.200000,...,0.141421,0.141421,0.163299,0.189737,0.141421,0.189737,0.220248,0.100000,0.141421,1.000000

In [79]:
def get_top_k_cuisines_for_user(user_id, k=5):
    # Find similar users to the target user
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:k+1].index

    # Get the cuisines preferred by similar users
    top_k_cuisines = user_cuisine_matrix.loc[similar_users].sum().sort_values(ascending=False)[:k].index

    return top_k_cuisines

In [80]:
user_id_to_recommend = 'U1016'  # Replace with the user ID you want to recommend cuisines for
top_k_cuisines = get_top_k_cuisines_for_user(user_id_to_recommend, k=5)
print(f"Top-K cuisines for user {user_id_to_recommend}:")
print(top_k_cuisines)

Top-K cuisines for user U1016:
Index(['American', 'Regional', 'Japanese', 'Barbecue', 'Afghan'], dtype='object', name='Rcuisine')